# Stage 1: Build React Vite
FROM node:18-alpine AS build

WORKDIR /app

# Copy dependencies dulu (cache lebih efisien)
COPY package*.json ./

RUN npm install

# Copy semua source code
COPY . .

# Build project Vite
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:latest

# Copy hasil build Vite ke Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Copy custom nginx config (untuk SPA routing)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
